"""Add User.email

Revision ID: b4e8dea4eed8
Revises: 9e25e221584c
Create Date: 2024-12-09 19:05:27.908146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4e8dea4eed8'
down_revision: Union[str, None] = '9e25e221584c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_user', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_user', 'email')
    # ### end Alembic commands ###
