"""Add ChatRoom

Revision ID: d613a2e91bd8
Revises: 9ffa5a62cef1
Create Date: 2024-12-12 14:44:03.294464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd613a2e91bd8'
down_revision: Union[str, None] = '9ffa5a62cef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chat_messages', sa.Column('chat_room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat_messages', 'chat_room', ['chat_room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_column('chat_messages', 'chat_room_id')
    op.drop_table('chat_room')
    # ### end Alembic commands ###
